import '../models/calculator_key.dart';

class CalculatorLayout {
  static const List<CalculatorKey> keys = [
    CalculatorKey(label: '!', value: '!', col: 0, row: 0, isExpandedOnly: true),
    CalculatorKey(label: '^', value: '^', col: 1, row: 0, isExpandedOnly: true),
    CalculatorKey(
      label: '√x',
      value: '√',
      col: 2,
      row: 0,
      isExpandedOnly: true,
    ),
    CalculatorKey(
      label: '³√x',
      value: '³√',
      col: 3,
      row: 0,
      isExpandedOnly: true,
    ),
    CalculatorKey(label: '(', value: '(', col: 0, row: 1, isExpandedOnly: true),
    CalculatorKey(label: ')', value: ')', col: 1, row: 1, isExpandedOnly: true),
    CalculatorKey(
      label: 'x²',
      value: '²',
      col: 2,
      row: 1,
      isExpandedOnly: true,
    ),
    CalculatorKey(
      label: 'x³',
      value: '³',
      col: 3,
      row: 1,
      isExpandedOnly: true,
    ),
    CalculatorKey(label: 'AC', value: 'AC', col: 0, row: 2),
    CalculatorKey(
      label: '⌫',
      value: '⌫',
      col: 1,
      row: 2,
      historyCol: 3,
      historyRow: 0,
      isVisibleInHistory: true,
    ),
    CalculatorKey(
      label: '%',
      value: '%',
      col: 2,
      row: 2,
      historyCol: 3,
      historyRow: 1,
      isVisibleInHistory: true,
    ),
    CalculatorKey(
      label: '÷',
      value: '÷',
      col: 3,
      row: 2,
      isVisibleInHistory: true,
    ),
    CalculatorKey(label: '7', value: '7', col: 0, row: 3),
    CalculatorKey(label: '8', value: '8', col: 1, row: 3),
    CalculatorKey(label: '9', value: '9', col: 2, row: 3),
    CalculatorKey(
      label: '×',
      value: '×',
      col: 3,
      row: 3,
      isVisibleInHistory: true,
    ),
    CalculatorKey(label: '4', value: '4', col: 0, row: 4),
    CalculatorKey(label: '5', value: '5', col: 1, row: 4),
    CalculatorKey(label: '6', value: '6', col: 2, row: 4),
    CalculatorKey(
      label: '-',
      value: '-',
      col: 3,
      row: 4,
      isVisibleInHistory: true,
    ),
    CalculatorKey(label: '1', value: '1', col: 0, row: 5),
    CalculatorKey(label: '2', value: '2', col: 1, row: 5),
    CalculatorKey(label: '3', value: '3', col: 2, row: 5),
    CalculatorKey(
      label: '+',
      value: '+',
      col: 3,
      row: 5,
      isVisibleInHistory: true,
    ),
    CalculatorKey(label: 'EXP', value: 'EXP', col: 0, row: 6),
    CalculatorKey(label: '0', value: '0', col: 1, row: 6),
    CalculatorKey(label: '.', value: '.', col: 2, row: 6),
    CalculatorKey(
      label: '=',
      value: '=',
      col: 3,
      row: 6,
      isVisibleInHistory: true,
    ),
  ];
}
