class RoastFallbacks {
  static const List<String> emptyHistory = [
    "Do some math first. I can't judge an empty screen.",
    "I need actual numbers to work with. Type something.",
    "Nothing to see here. Hit some buttons.",
    "Blank screen, blank mind. Do some math.",
    "You haven't calculated anything. Are you just staring at the UI?",
    "Give me some numbers and I'll give you some reality.",
    "Math doesn't solve itself. Get typing.",
    "Waiting on you to make a mathematical mistake.",
    "Screen is looking a bit empty, much like your math skills.",
    "I'm ready to roast, but you need to calculate something first.",
    "Hit a number. Any number.",
    "This calculator only works if you actually press the keys.",
    "I can't roast the void. Calculate something.",
    "Still waiting for your first equation.",
    "Don't be shy, do some math.",
    "Type an equation. I promise I'll only judge you a little.",
    "You're just staring at a calculator. Do something.",
    "I need data to insult you properly.",
    "Start calculating so I can start judging.",
    "Are you afraid of numbers? Type something.",
    "This is a calculator, not a mirror. Stop staring.",
    "Math is required for this app to be fun.",
    "I'm bored. Do some math.",
    "You opened a calculator just to look at zero?",
    "The keys are right there. Press them.",
    "Give me an equation, any equation.",
    "I'm a chill coworker, but even I need you to do some work first.",
    "Waiting for input. Literally.",
    "Zero calculations detected. Zero respect given.",
    "You know how a calculator works, right?",
    "Type numbers. Hit equals. Get roasted.",
    "I can't work with a blank canvas.",
    "Show me what you got. Mathematically.",
    "Are we doing math today or just hanging out?",
    "Press some digits. Make a mistake. It's fine.",
    "I need calculation history to generate the insults.",
    "Awaiting your mathematical genius.",
    "Come on, just one little addition problem?",
    "I'm powered by your math mistakes. Feed me.",
    "Nothing calculated yet. I'm taking a nap.",
    "Wake me up when you actually calculate something.",
    "Still empty. Are you contemplating the universe?",
    "Math. Do you speak it?",
    "I need some digits on the board.",
    "Let's see those math skills. Start typing.",
    "I can't roast nothing.",
    "You're making this very easy for me. Do some math.",
    "Input required for judgment.",
    "Just give me a simple 1+1. I dare you.",
    "Waiting for you to prove you know numbers.",
  ];

  static const List<String> greetings = [
    "Welcome to RoastCalc. Do some math, I'll start judging in 5 minutes.",
    "I'm awake. Start calculating, the first roast drops in 5.",
    "Roast engine warming up. Check back in 5 minutes.",
    "Welcome. I'll need about 5 minutes of your math history to find the flaws.",
    "Ready when you are. The roasting begins in 5 minutes.",
    "Oh, you're back. Let's see how bad your math is today.",
    "Calculator initialized. Judgment protocols starting in 5.",
    "Hey. Give me 5 minutes to observe your math habits.",
    "I'm your chill coworker. I'll roast your math in 5 minutes.",
    "Welcome back to the judgment zone. Give me 5.",
    "Logging your inputs. I'll have a summary of your failures in 5 minutes.",
    "Hello. I'm silently judging you for the next 5 minutes.",
    "Math time. I'll review your work in 5.",
    "Let's do this. I'll check your progress in 5 minutes.",
    "Welcome. Prepare to be humbled in exactly 5 minutes.",
    "I'm online. Give me 5 minutes of data.",
    "Ready to calculate? I'll be ready to roast in 5.",
    "Hey there. Start typing, I'll drop by in 5 minutes.",
    "Initializing... Judgment will commence in 5 minutes.",
    "Welcome to the roast zone. You have a 5-minute head start.",
    "I'm here. I'm judging. But I'll wait 5 minutes to say anything.",
    "Let's see if you improved. I'll tell you in 5.",
    "Good to see you. You have 5 minutes to impress me.",
    "Booting up. Roasts will be served in 5 minutes.",
    "Welcome back. The 5-minute countdown begins now.",
    "I'll let you warm up for 5 minutes before I start roasting.",
    "Hello. Do some math. I'll be back in 5.",
    "I'm monitoring your keystrokes. Assessment in 5 minutes.",
    "Let's get this over with. I'll check your work in 5.",
    "Welcome. Your 5-minute grace period has started.",
    "I'm awake. Don't disappoint me. See you in 5.",
    "Calculator ready. Roasts ready in 5 minutes.",
    "Hey. I'm giving you 5 minutes to make a fool of yourself.",
    "Start calculating. I'll start the commentary in 5.",
    "Welcome. I'll let you do math in peace for exactly 5 minutes.",
    "I'm online and unimpressed. Check back in 5.",
    "Let's see those numbers. I'll review in 5 minutes.",
    "Hello again. The 5-minute timer is ticking.",
    "Welcome. I'll try to hold my tongue for 5 minutes.",
    "Ready for math. Ready for roasts in 5.",
    "Hey. I'll evaluate your life choices in 5 minutes.",
    "Welcome back. Your math better be good. I'll check in 5.",
    "I'm here to help, and by help I mean roast you in 5 minutes.",
    "Calculator is on. Roast engine starts in 5.",
    "Hello. You have 5 minutes before I start talking.",
    "Welcome. Let's see what you mess up in the next 5 minutes.",
    "I'm watching. I'll give my feedback in 5.",
    "Hey there. The 5-minute wait begins.",
    "Welcome. I'll be judging you silently for 5 minutes.",
    "Booted up. I'll have a roast ready in 5 minutes.",
  ];

  static const List<String> serverError = [
    "I tried to roast you, but the server cringed too hard. Try again later.",
    "The cloud rejected your math. Try again.",
    "Server is down. Probably because of that last equation.",
    "I have a great roast for this, but the server won't let me send it.",
    "Error 500: Your math broke my backend.",
    "The AI refused to look at your math. Server error.",
    "Server timed out trying to make sense of your calculations.",
    "Backend crashed. Your math is literally destructive.",
    "I tried to connect, but the server just sighed and disconnected.",
    "Server error. Even machines need a break from your math.",
    "The API is currently ignoring us. Try again later.",
    "Cloud services are down. Consider it mercy.",
    "My server is broken. Just like your understanding of algebra.",
    "Connection failed. The server is hiding from your math.",
    "Error fetching roast. The server is speechles.",
    "Backend error. Your math is too powerful.",
    "Server is offline. Probably rethinking its life choices.",
    "I can't reach the AI. You're safe for now.",
    "Server dropped the connection. I don't blame it.",
    "Error connecting to judgment protocols.",
    "The roast server is taking a mental health day.",
    "Failed to load roast. The server is currently facepalming.",
    "Backend issue. Check back when your math improves.",
    "Server error. The AI is too confused to respond.",
    "Could not fetch roast. Consider yourself lucky.",
  ];

  static const List<String> offline = [
    "No internet? Don't worry, your math is still questionable offline.",
    "You are offline. I am judging you locally.",
    "No connection. Pretend I said something devastating about your math.",
    "Wi-Fi is down. Your calculation skills remain awful.",
    "I need the internet to generate a proper roast. Get connected.",
    "You're offline. Did you calculate your internet bill wrong?",
    "No signal. Just me, you, and your terrible math.",
    "Offline mode. I can't roast you, but I'm still disappointed.",
    "Connect to Wi-Fi if you want to hear what I really think.",
    "Internet is gone. My judgment is forever.",
    "You are disconnected. Much like your math is from reality.",
    "Offline. Reconnect to resume the roasting.",
    "No network. You're spared from my commentary. For now.",
    "Wi-Fi required for advanced insults.",
    "You're offline. I'll just shake my head in silence.",
    "No connection. I'll save my roasts for later.",
    "Internet down. At least your math mistakes are private now.",
    "Offline. The AI cannot reach you here.",
    "Connect to a network. I have things to say.",
    "No Wi-Fi. I'm judging your router setup now.",
    "Offline mode activated. Roasts deactivated.",
    "You're off the grid. Your math is still basic though.",
    "No internet. I'll just assume your last calculation was wrong.",
    "Disconnected. Just like your logic.",
    "Get some internet if you want the full chill coworker experience.",
  ];
}
