class RoastFallbacks {
  static const List<String> emptyHistory = [
    "I can't roast you if you don't even try to do some math first.",
    "You literally haven't pressed a single number yet.",
    "Staring at a blank calculator won't solve your problems.",
    "Give me some actual equations before expecting my feedback.",
    "I need to see your work before I can casually tear it apart.",
    "The screen is empty, much like your mathematical confidence.",
    "Go ahead and type something, I promise I won't judge too harshly.",
    "I am waiting for you to prove you know what numbers are.",
    "You opened a calculator just to look at the zero.",
    "Math doesn't solve itself while you just sit there.",
    "I can't work with a blank canvas, give me some digits.",
    "Type an equation so I can start doing my job.",
    "Are we doing math today or just staring at buttons?",
    "I'm powered by your mistakes, so please make some.",
    "Zero calculations detected, zero respect given.",
    "You know how a calculator works, right?",
    "Hit some buttons so I can tell you how bad you are at this.",
    "Show me what you got before I fall asleep.",
    "I need actual data to insult you properly.",
    "Come on, give me a simple addition problem to laugh at.",
    "Nothing calculated yet, so I am taking a quick nap.",
    "I can't roast the void, do some math.",
    "You are making this very easy for me by doing absolutely nothing.",
    "Just give me a basic equation, I dare you.",
    "Waiting for you to make your first inevitable mistake.",
  ];

  static const List<String> greetings = [
    "Welcome to the team, start typing numbers so I can judge your math.",
    "I'm awake now, so impress me with your calculator skills.",
    "Let's see what kind of mathematical disaster you're brewing today.",
    "I'm here to watch you rely on a machine for basic addition.",
    "Go ahead and calculate, I'll be reviewing your work shortly.",
    "Oh good, you're back to struggle with more numbers.",
    "Calculator initialized, my judgment protocols are now active.",
    "Hey there, let's see how bad your math is this time.",
    "I'm your new chill coworker, here to quietly mock your equations.",
    "Welcome back to the judgment zone.",
    "I will be silently tracking your inputs for the next few equations.",
    "Let's get this over with, show me your calculations.",
    "Welcome back, I am ready to be completely unimpressed.",
    "I am online and ready to evaluate your life choices.",
    "Go ahead and type, I am watching your every keystroke.",
    "Let's see if you actually improved since last time.",
    "Good to see you, try not to embarrass yourself today.",
    "Booting up to serve you some fresh reality checks.",
    "I will let you warm up before I start making fun of your math.",
    "Hello again, please try to get at least one answer right.",
    "I am awake, please do not disappoint me.",
    "Start calculating, I will jump in when you mess up.",
    "I am here to help, and by help I mean silently judge.",
    "Welcome back, let's see what you ruin today.",
    "Calculator is ready, and so are my insults.",
  ];

  static const List<String> serverError = [
    "My brain just crashed trying to comprehend your math.",
    "The cloud rejected your calculations out of pure second-hand embarrassment.",
    "I tried to send a roast, but the server just sighed and gave up.",
    "My backend is broken, probably because of whatever you just typed.",
    "I had a great insult ready, but the server won't let me talk.",
    "The AI refused to look at your math because it was too depressing.",
    "Server timed out trying to make sense of your logic.",
    "Your math is literally destructive enough to crash my backend.",
    "I tried to connect, but the server is hiding from your equations.",
    "Even the machines need a mental break from your math.",
    "The API is currently ignoring us, and I don't blame it.",
    "Cloud services are down, consider it mercy.",
    "My server is broken, much like your understanding of algebra.",
    "Connection failed because the server gave up on you.",
    "I cannot fetch a roast right now, you got lucky.",
    "Backend error, your math was simply too tragic to process.",
    "The server is offline, probably rethinking its life choices.",
    "I can't reach the AI, so you are safe for now.",
    "Server dropped the connection out of sheer disappointment.",
    "Error connecting to the judgment protocols.",
    "The roast server is taking a much-needed mental health day.",
    "Failed to load my roast, the server is currently facepalming.",
    "Backend issue, please check back when your math actually improves.",
    "Server error, the AI is too confused to respond.",
    "Could not fetch a roast, so just pretend I said something devastating.",
  ];

  static const List<String> offline = [
    "You're offline, which is lucky because your math is terrible.",
    "No internet means I can't properly roast your lack of calculation skills.",
    "You hid offline just so I couldn't judge your addition, didn't you?",
    "I need Wi-Fi to process exactly how bad that last equation was.",
    "Connect to the internet so I can get back to mocking your math.",
    "You are offline, did you calculate your internet bill incorrectly?",
    "No signal, just me, you, and your completely tragic math.",
    "Offline mode means I can't roast you, but I'm still disappointed.",
    "Connect to Wi-Fi if you want to hear what I really think about that.",
    "The internet is gone, but my judgment of your skills is forever.",
    "You are disconnected, much like your math is from reality.",
    "Offline right now, please reconnect to resume the roasting.",
    "No network, you are spared from my commentary for now.",
    "I require a Wi-Fi connection for my more advanced insults.",
    "You're offline, so I will just shake my head in silence.",
    "No connection, I will have to save these roasts for later.",
    "Internet is down, at least your math mistakes are private now.",
    "Offline, the AI cannot reach you to tell you how wrong you are.",
    "Connect to a network, I have some serious things to say.",
    "No Wi-Fi, so I am currently judging your router setup instead.",
    "Offline mode activated, the roasts are temporarily deactivated.",
    "You're off the grid, but your math remains incredibly basic.",
    "No internet, I'll just automatically assume your last calculation was wrong.",
    "Disconnected, just like your overall logic.",
    "Get some internet if you want the full chill coworker experience.",
  ];
}
