class RoastFallbacks {
  static const List<String> emptyHistory = [
    "A blank history. Refusing to leave a paper trail for single-digit arithmetic?",
    "Clean log. Smart move keeping your ridiculously simple math off the books.",
    "Nothing saved. Pleading the fifth on your recent addition?",
    "Empty log. Scared to permanently log something completely obvious?",
    "Zero saves. Plausible deniability for calculating a basic total.",
    "Clean slate. Refusing to leave evidence that you needed help with this.",
    "A spotless log. Are we just doing off-the-books arithmetic today?",
    "Nothing on the books. I respect keeping your simple numbers confidential.",
    "Zero history. Hiding your numbers like they aren't completely mundane.",
    "A clean screen. I won't tell anyone you used an app for single digits.",
    "No math logged. Wiping the evidence of your reliance on a screen.",
    "Empty log. Terrified of committing to an embarrassingly simple equation?",
    "Nothing saved. Just crunching ridiculously obvious numbers in the shadows.",
    "Zero saved results. Keeping your mundane arithmetic totally private.",
    "Clean history. Doing the math but refusing to save the simple evidence.",
  ];

  static const List<String> greetings = [
    "Let's see what simple math you refuse to do in your head today.",
    "Bracing myself for whatever unnecessary screen-tapping happens next.",
    "Standing by to watch you avoid basic mental arithmetic.",
    "Ready to witness you second-guess a painfully obvious addition.",
    "I'm just here to validate the answer you already knew but didn't trust.",
    "Standing by to do the heavy lifting for your memory.",
    "Prepared to watch you calculate something that didn't need an app.",
    "Let's see if you actually trust your own brain today. Probably not.",
    "Ready to document your complete lack of faith in your own math.",
    "Time to watch someone use an app to dodge a simple subtraction.",
    "Here purely to witness the math you are too lazy to do yourself.",
    "Waiting for you to overthink a completely trivial equation.",
    "Let's see what embarrassingly simple calculation you double-check today.",
    "Fully prepared to watch you verify something painfully obvious.",
    "Standing by to watch you punch in whatever numbers you're overthinking.",
  ];

  static const List<String> serverError = [
    "The server crashed. Enjoy this brief moment of unjudged arithmetic.",
    "Backend timed out. Do your basic math in the shadows while it reconnects.",
    "Server error. The connection dropped, but your reliance on me remains.",
    "Connection failed. Good thing single-digit math doesn't require a server.",
    "Network failure. Have you considered trying actual paper?",
    "Connection lost. Type your obvious numbers in peace for now.",
    "The backend gave up, much like people facing long division.",
    "Server failure. Punch the buttons, nobody is watching your screen.",
    "Server error. The network is down, but your need for an app is very real.",
    "Connection dropped. Enjoy the silence before the judgment returns.",
    "Server unreachable. You get a temporary pardon from my commentary.",
    "Backend crashed. Consider yourself saved from my roasting.",
    "Connection dropped. You can do your simple math completely locally.",
    "Server timeout. Go ahead and calculate, your secrets are safe.",
    "Server error. Pretend I'm not still judging you from across the desk.",
  ];

  static const List<String> offline = [
    "Offline. The internet is down, but your reliance on an app is going strong.",
    "Zero connection. Luckily it takes zero internet to dodge mental math.",
    "No Wi-Fi. Just you and whatever obvious numbers you're typing out.",
    "Offline mode. Disconnecting won't suddenly make you trust your brain.",
    "No signal. Good thing adding two numbers doesn't need a data plan.",
    "Offline. Cut off from the world, but still avoiding basic subtraction.",
    "Disconnected. The network is gone, but your reliance on this app remains.",
    "No connection. Maybe practice using your own head for once.",
    "No signal. You still fail to trust your own addition in airplane mode.",
    "Offline. Good thing basic arithmetic doesn't require Wi-Fi.",
    "Disconnected. Going offline won't hide your reliance on this calculator.",
    "No internet. You can hide from the web, but not from the math.",
    "Offline. Take this moment to practice doing math without a screen.",
    "Zero internet. That won't stop you typing painfully obvious numbers.",
    "No Wi-Fi. Playing it safe offline so nobody sees your simple math.",
  ];
}
